name: eduarno
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animated_float_action_button: ^1.0.3
  badges: ^2.0.1
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.1
  custom_radio_grouped_button: ^2.0.0
  custom_switch: ^0.0.1
  dropdown_search: any
  file_picker: ^4.0.0
  firebase_core: any
  firebase_messaging: ^10.0.5
  flutter:
    sdk: flutter
  flutter_html: ^2.1.1
  flutter_launcher_icons: ^0.9.0
  page_transition: "^1.1.6"
  flutter_local_notifications: ^8.1.1+1
  flutter_multiselect: ^1.0.0
  flutter_statusbarcolor: ^0.2.3
  flutter_svg: ^0.22.0
  flutter_switch: ^0.3.2
  fluttertoast: ^7.1.8
  timeago: ^3.1.0
  hive: ^2.0.4
  http: ^0.13.3
  http_parser: ^4.0.0
  image_picker: ^0.8.3+2
  intl: ^0.17.0
  intl_phone_field: ^2.0.1
  lint: ^1.6.0
  mime_type: ^1.0.0
  modal_bottom_sheet: ^2.0.0
  multi_select_flutter: ^4.0.0
  otp_text_field: ^1.1.1
  path_provider: ^2.0.1
  pedantic: ^1.11.1
  pinput: ^1.2.0
  provider: ^5.0.0
  radio_button_form_field: ^0.0.4
  shared_preferences: any
  shimmer: ^2.0.0
  solid_bottom_sheet: ^0.1.10
  splashscreen: ^1.3.5
  weekday_selector: ^1.0.0
  razorpay_flutter: ^1.2.7
  url_launcher: ^6.0.9  
  rounded_loading_button: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
  #    - assets/resultcup.png
  #    - assets/man.png
  #    - assets/Eduarno_bg.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-ExtraBold.ttf
          weight: 800
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto/Roboto-Regular.ttf
          weight: 400
